name: Deploy to Firebase & Cloud Run

on:
  push:
    branches: ["fresh_start", "main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      IMAGE_NAME: jps-web

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Deploy Firestore rules & Functions
        run: |
          cd functions
          npm ci || npm install
          npm run build
          cd -
          firebase deploy --project "$GCP_PROJECT_ID" --only firestore:rules,functions

      - name: Build container (Cloud Build)
        run: |
          gcloud builds submit --tag gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $IMAGE_NAME \
            --image gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:${{ github.sha }} \
            --region $GCP_REGION \
            --allow-unauthenticated \
            --port 8080 \
            --memory 512Mi \
            --cpu 1 \
            --max-instances 20 \
            --min-instances 0 \
            --timeout 60s 
