name: Deploy to Firebase (manual)

on:
  workflow_dispatch:  # <-- manual trigger only

permissions:
  contents: read
  id-token: write

concurrency:
  group: firebase-deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  FIREBASE_CLI_LOGIN: ci

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Google auth via Workload Identity Federation
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      # Build the SPA
      - name: Build web
        run: |
          cd web
          npm ci || npm install
          npm run build
          cd -

      # Prebuild Functions (firebase.json also builds, this fails fast)
      - name: Build functions
        run: |
          cd functions
          npm ci || npm install
          npm run build
          cd -

      - name: Deploy Hosting + Functions
        run: |
          firebase deploy --project "$GCP_PROJECT_ID" --only functions,hosting --force
